"use client";
import { useState } from "react";
import type { ContentJob, JobLog } from "@/lib/types";
import type { YoutubeAnalytics, YoutubeChannelStats } from "@/lib/youtube";
const labels: Record<string, string> = { queued: "Queued", researching: "Researching", scripting: "Scripting", generating_voice: "Voice", generating_visuals: "Visuals", assembling: "Assembling", thumbnail: "Thumbnail", quality_check: "Quality check", uploading: "Uploading", scheduled: "Scheduled", published: "Published", failed: "Failed" };
const pipelineStages = ["Research", "Script", "Voice", "Video", "Title", "Description", "Tags & Keywords", "SEO", "YouTube Upload", "Publish"] as const;
type PipelineStatus = "pending" | "active" | "done" | "error";
type JobState = ContentJob["state"];
const doneByState: JobState[] = ["scripting", "generating_voice", "generating_visuals", "assembling", "thumbnail", "quality_check", "uploading", "scheduled", "published"];
const activeByState: JobState[] = ["researching", "scripting", "generating_voice", "generating_visuals", "assembling", "thumbnail", "quality_check", "uploading"];
const states = (...values: JobState[]) => values;
function compact(value: number) { return new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(value); }
function hours(value: number) { return value < 10 ? value.toFixed(1) : compact(value); }
function changePercent(current: number, previous: number) { if (previous === 0) return current > 0 ? "+100%" : "0%"; const change = ((current - previous) / previous) * 100; return `${change >= 0 ? "+" : ""}${change.toFixed(0)}%`; }
function stageStatus(job: ContentJob | null, index: number): PipelineStatus {
  if (!job) return "pending";
  if (job.state === "published") return "done";
  const complete = [
    doneByState.includes(job.state),
    doneByState.includes(job.state),
    states("generating_visuals", "assembling", "thumbnail", "quality_check", "uploading", "scheduled").includes(job.state),
    states("assembling", "thumbnail", "quality_check", "uploading", "scheduled").includes(job.state),
    Boolean(job.title) && states("generating_voice", "generating_visuals", "assembling", "thumbnail", "quality_check", "uploading", "scheduled").includes(job.state),
    Boolean(job.description) && states("generating_voice", "generating_visuals", "assembling", "thumbnail", "quality_check", "uploading", "scheduled").includes(job.state),
    Boolean(job.tags?.length) && states("generating_voice", "generating_visuals", "assembling", "thumbnail", "quality_check", "uploading", "scheduled").includes(job.state),
    Boolean(job.seo) && states("generating_voice", "generating_visuals", "assembling", "thumbnail", "quality_check", "uploading", "scheduled").includes(job.state),
    states("scheduled", "published").includes(job.state),
    false
  ];
  if (job.state === "failed") {
    const failureIndex = !job.research ? 0 : !job.script ? 1 : !job.voiceId ? 2 : !job.videoId ? 3 : 8;
    if (index === failureIndex) return "error";
    return index < failureIndex || complete[index] ? "done" : "pending";
  }
  if (complete[index]) return "done";
  const activeStage = job.state === "researching" ? 0 : job.state === "scripting" ? 1 : job.state === "generating_voice" ? 2 : job.state === "generating_visuals" ? 3 : job.state === "assembling" || job.state === "thumbnail" || job.state === "quality_check" ? 4 : job.state === "uploading" ? 8 : -1;
  return activeByState.includes(job.state) && index === activeStage ? "active" : "pending";
}
function stageIcon(status: PipelineStatus) { return status === "done" ? "✓" : status === "error" ? "!" : status === "active" ? "•" : ""; }
export function Dashboard({ initialJobs, initialLogs, configured, youtubeConnected, channelStats, youtubeAnalytics }: { initialJobs: ContentJob[]; initialLogs: JobLog[]; configured: boolean; youtubeConnected: boolean; channelStats: YoutubeChannelStats | null; youtubeAnalytics: YoutubeAnalytics | null }) {
  const [jobs, setJobs] = useState(initialJobs); const [logs, setLogs] = useState(initialLogs); const [busy, setBusy] = useState(false);
  const run = async (id: string) => { setBusy(true); const res = await fetch(`/api/jobs/${id}/run`, { method: "POST" }); const data = await res.json(); if (data.job) { setJobs((all) => all.map((j) => j.id === id ? data.job : j)); setLogs((all) => [{ id: crypto.randomUUID(), jobId: id, level: res.ok ? "info" : "error", message: res.ok ? `Live worker completed: ${data.job.state.replaceAll("_", " ")}.` : data.error, createdAt: new Date().toISOString() }, ...all]); } setBusy(false); };
  const today = jobs.filter(j => new Date(j.scheduledFor).toDateString() === new Date().toDateString());
  const activeJob = jobs.find(j => !["scheduled", "published", "failed"].includes(j.state)) ?? jobs[0] ?? null;
  const allDone = jobs.some(j => j.state === "published") && jobs.every(j => j.state === "published" || j.state === "scheduled");
  return <main><aside><div className="brand"><span>UWF</span> YT Agent</div><nav><a className="active">Overview</a><a>Content pipeline</a><a>Schedule</a><a>Video library</a><a href="/settings">Settings</a></nav><div className="sidebar-foot">Operations console<br/><small>v1.0.0</small></div></aside><section className="content"><header><div><p className="eyebrow">CONTENT OPERATIONS</p><h1>Good morning, UWF.</h1><p className="muted">Your autonomous publishing desk is ready.</p></div>{youtubeConnected ? <span className="button connected-button">✓ Connected</span> : <a className="button" href="/api/youtube/oauth">{configured ? "Connect YouTube" : "Configure YouTube"}</a>}</header>
    <div className="metrics"><Metric name="Today’s jobs" value={`${today.length}/1`} hint="Publishing plan" /><Metric name="Pipeline active" value={String(jobs.filter(j => !["scheduled", "published", "failed"].includes(j.state)).length)} hint="Content in progress" /><Metric name="YouTube" value={youtubeConnected ? "Connected" : configured ? "Ready" : "Setup needed"} hint={youtubeConnected ? "Uploads authorized" : configured ? "Authorization required" : "Add OAuth secrets"} /><Metric name="API health" value="Healthy" hint="Server responding" /></div>
    <div className="grid"><section className="panel wide"><div className="panel-title"><div><p className="eyebrow">TODAY</p><h2>Publishing queue</h2></div><span className="muted">1 video / day</span></div><div className="jobs">{jobs.slice(0, 5).map(job => <article className="job" key={job.id}><div className="job-icon">{job.format === "short" ? "S" : "▶"}</div><div className="job-main"><strong>{job.title}</strong><span>{job.topic} · {job.format === "short" ? "30–60 sec Short" : "5–10 min video"}</span></div><time>{new Date(job.scheduledFor).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time><span className={`badge ${job.state}`}>{labels[job.state]}</span><button disabled={busy || ["scheduled", "published", "failed"].includes(job.state)} onClick={() => run(job.id)}>{busy ? "Working…" : "Run live"}</button></article>)}</div></section>
    <section className="panel"><p className="eyebrow">CHANNEL CONNECTION</p><h2>YouTube Studio</h2><div className={`connection ${youtubeConnected ? "ok" : "warn"}`}><b>{youtubeConnected ? "✓ Connected" : configured ? "Authorization required" : "Action required"}</b><p>{youtubeConnected ? `${channelStats?.title ?? "Your YouTube channel"} is authorized for uploads.` : configured ? "Connect your Google account to authorize uploads." : "Add YouTube OAuth credentials in your server environment."}</p></div>{youtubeConnected ? <span className="connected-note">Google account authorized</span> : <a className="text-link" href="/api/youtube/oauth">Open authorization →</a>}</section>
    <section className="panel wide analytics-panel"><div className="panel-title"><div><p className="eyebrow">YOUTUBE ANALYTICS</p><h2>{channelStats?.title ?? "Channel analytics"}</h2></div><span className="muted">Live channel totals</span></div>{channelStats ? <><div className="analytics-grid"><Metric name="Subscribers" value={compact(channelStats.subscriberCount)} hint="Current subscribers" /><Metric name="Total views" value={compact(channelStats.viewCount)} hint="Lifetime channel views" /><Metric name="Videos" value={compact(channelStats.videoCount)} hint="Published videos" /><Metric name="Watch time" value={youtubeAnalytics ? `${hours(youtubeAnalytics.watchTimeHours)}h` : "—"} hint={youtubeAnalytics ? `Last ${youtubeAnalytics.recentDays} days` : "Analytics API needed"} /></div><div className="recent-performance"><div><p className="eyebrow">RECENT PERFORMANCE</p><h3>Last 7 days</h3></div>{youtubeAnalytics ? <div className="performance-grid"><div><b>{compact(youtubeAnalytics.recentViews)}</b><span>Views · {changePercent(youtubeAnalytics.recentViews, youtubeAnalytics.previousViews)}</span></div><div><b>{compact(youtubeAnalytics.recentSubscribers)}</b><span>Subscribers · {changePercent(youtubeAnalytics.recentSubscribers, youtubeAnalytics.previousSubscribers)}</span></div><div><b>{hours(youtubeAnalytics.watchTimeHours)}h</b><span>Watch time</span></div></div> : <p className="muted">Reconnect YouTube after enabling the YouTube Analytics API so watch time and recent performance can load.</p>}</div></> : <div className="analytics-empty">{youtubeConnected ? "Channel analytics are temporarily unavailable." : "Connect YouTube to load subscriber, view, and video statistics."}</div>}</section>
    <section className="panel wide"><div className="panel-title"><div><p className="eyebrow">AUTOMATION PIPELINE</p><h2>Production stages</h2></div><span className={`pipeline-overall ${allDone ? "all-done" : activeJob?.state === "failed" ? "has-error" : "in-progress"}`}>{allDone ? "✓ All Done" : activeJob?.state === "failed" ? "✕ Error" : "Live worker execution"}</span></div><div className="pipeline-checklist">{pipelineStages.map((stage, index) => { const status = stageStatus(activeJob, index); return <div key={stage} className={`pipeline-stage ${status}`}><b>{status === "pending" ? index + 1 : stageIcon(status)}</b><span>{stage}</span><em>{status === "done" ? "Complete" : status === "error" ? "Error" : status === "active" ? "In progress" : "Pending"}</em></div>; })}</div><p className="muted pipeline-note">{allDone ? "All production stages completed and the video has been published to YouTube." : "Each stage now reflects the live worker status: ✓ complete, • in progress, ! error, or pending."}</p></section>
    <section className="panel wide"><div className="panel-title"><div><p className="eyebrow">ACTIVITY</p><h2>Pipeline logs</h2></div></div><div className="logs">{logs.slice(0, 6).map(log => <p key={log.id}><span className={log.level}>●</span> {log.message}<time>{new Date(log.createdAt).toLocaleTimeString()}</time></p>)}</div></section>
    <section className="panel"><p className="eyebrow">SCHEDULE RULE</p><h2>Weekly format</h2><p className="schedule"><b>Friday + Sunday</b><br/>YouTube Shorts<br/><br/><b>Monday–Thursday, Saturday</b><br/>Long-form videos</p></section></div></section></main>;
}
function Metric({ name, value, hint }: { name: string; value: string; hint: string }) { return <article className="metric"><p>{name}</p><strong>{value}</strong><span>{hint}</span></article>; }
